spring:
  application:
    name: api-customer

  jpa:
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
    open-in-view: false

  datasource:
    url: jdbc:postgresql://localhost:5433/BankApi
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    addresses: amqps://jpgtmedc:IcbxOrLUyPGZfNQJTvF7VgvyUOoT-3dn@jackal.rmq.cloudamqp.com/jpgtmedc
    dynamic: true
    ssl:
      enabled: true

customer:
  exchange:
    name: customer.exchange
  queue:
    name: customer.queue
  routing:
    key: customer.event

server:
  port: 9595
  servlet:
    context-path: /api/v1